olimorris/neotest-rspec

lua/neotest-rspec/init.lua
Match `context` blocks as a namespace definition as well as `describe`.
Also simplify the predicate to `eq` for test definition.
=> feat: recognize describe blocks as namespace

spec/class_method_spec.rb, spec/instance_method_spec.rb
In our codebase I noticed that specs using [class/instance method naming conventions](https://www.betterspecs.org/#describe) either have no results or seem to get results from unrelated tests.
It looks like the RSpec example `full_description` output doesn't seem to match up with the Treesitter names we generate.
=> test: examples for common naming conventions

lua/neotest-rspec/init.lua
Enables subprocess parsing.
See https://github.com/nvim-neotest/neotest/issues/13#issuecomment-1260570396
=> feat(treesitter): pass position_id as string

lua/neotest-rspec/init.lua
A test reuse strategy in RSpec is to consolidate shared blocks of code into `shared_examples` and include them into context blocks using `it_behaves_like`. These should probably be treated as test definitions.
=> feat: parse it_behaves_like as a test definition

Gemfile.lock, lua/neotest-rspec/init.lua, lua/neotest-rspec/utils.lua, test_engine/spec/basic_spec.rb, test_engine/spec/spec_helper.rb, tests/init_spec.lua, tests/utils_spec.lua
When you launch nvim from the root of a rails project with an engine and then try to run the engine tests things would break. 
Now there's some detection and some special parsing to make it work.
=> Support for Engine specs

lua/neotest-rspec/init.lua, tests/init_spec.lua
Implements the `filter_dir` method in the [neotest adapter interface](https://github.com/nvim-neotest/neotest/blob/master/lua/neotest/adapters/interface.lua#L14-L20)
This reduces the initial load time of the neotest plugin in large repos by a substantial margin (20s to 9s in my work rails repo)
Currently using some simple rules. If the path has "spec" in it, it's good. If it doesn't, and it's got a "/" in it, it's bad. 
These rules allow "engine/spec" to get picked up as well as "spec", but would miss "engine/something/spec"
afaik, that last case is not common or recommended? I'm fairly new to this whole ruby thing. So let me know if that's a problem.
=> Filter directories

lua/neotest-rspec/init.lua, spec/one_liner_syntax_spec.rb
Thanks for the great plugin!
I've run across a case that's not detected yet. It's possible to define "one-liner" tests with a multi-line block:
```ruby
it do
expect([]).to be_empty
end
```
I've added a treesitter query to detect this case.
=> feat: Support descriptionless it blocks

.github/workflows/ci.yml
Upgrades to `actions/checkout@v3` to resolve the following warning on CI runs:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2.
=> chore: upgrade github action

.github/workflows/ci.yml
* Use action to install the latest neovim. The deb is not available for the latest versions, see https://github.com/neovim/neovim/pull/22773
* No need to install nvim-treesitter. This is done in the Makefile
* Remove install dependencies step. The runner already has these dependencies see https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
I know the tests are failing right now but at least they fail faster 😅
=> chore: simplify ci workflow

lua/neotest-rspec/init.lua
Currently the match check can grab a spec path not at the root. I.e. for domains/example/spec/example_spec.rb it will match spec/example_spec.rb and use that spec folder as the root. This can cause the run to use the wrong root path if using something like packwerk. By specifying start of line in the regex we guarantee we are only checking the root spec.
=> Ensure we're only checking the start of the path

lua/neotest-rspec/init.lua, spec/one_liner_syntax/one_liner_syntax_spec.rb, spec/one_liner_syntax/one_liner_syntax_spec_04.commands, spec/one_liner_syntax/one_liner_syntax_spec_04.expected
Ref #50 
```
nvim --headless --clean \
-u tests/minimal_init.lua \
-c "PlenaryBustedDirectory tests/unit/core { minimal_init = 'tests/minimal_init.lua' }"
Starting...Scheduling: tests/unit/core/plugin_spec.lua
Scheduling: tests/unit/core/treesitter_installed_spec.lua
Scheduling: tests/unit/core/utils_spec.lua
========================================
Testing:        /home/eric/personal/neovim/neotest-rspec/tests/unit/core/plugin_spec.lua
Success ||      is_test_file matches rspec files
Success ||      is_test_file does not match plain ruby files
Success ||      filter_dir allows spec
Success ||      filter_dir allows sub directories one deep (for engines)
Success ||      filter_dir allows paths that contain spec
Success ||      filter_dir allows a long path with spec at the start
Success: …
```
=> fix: add a query to catch one liner

README.md, lua/neotest-rspec/config.lua, lua/neotest-rspec/init.lua
Hello, this PR adds support for running rspec in a docker container by adding a couple of new config options:
- `transform_spec_path` allows the spec path to be modified before being passed to rspec. When running in a docker container a relative path needs to be used instead of an absolute path.
- `results_path` allows the results file to be modified so that it's available to both the docker container and host.
=> feat: Add support for running rspec in a docker container.

lua/neotest-rspec/utils.lua, spec/included_examples/included_examples_spec.rb, spec/included_examples/shared_examples.rb, tests/unit/core/utils_spec.lua
add support for examples included with `it_behaves_like`
=> feat: add support for included examples

README.md, lua/neotest-rspec/init.lua
I have an RSpec test that uses data to generate tests such as:
```ruby
RSpec.describe SomeClass do
describe "some feature" do
FIXTURES.each do |method, path|
it "does something with the #{method} and #{path}" do
end
end
end
end
```
The problem is that running a typical `bundle exec rspec` with the runner will show this passing even if some of the generated tests fail. I can fix it by making my command `bundle exec rspec --fail-fast` however now the entire test file will fail if a single test does.
This PR enables someone to change the rspec command depending on the type of test they ran, which would fix my issue like so:
```lua
rspec_cmd = function(position_type)
if position_type == "test" then
return vim.tbl_flatten({
"bundle",
"exec",
"rspec",
"--fail-fast"
})
else
return …
```
=> [feat] Pass position_type to allow more rspec_cmd customization

Makefile, tests/minimal_init.lua
nvim-neotest requires external plugin nvim-nio to run. This was added as a breaking change in https://github.com/nvim-neotest/neotest/pull/337
=> tests: make sure we have external nio when running tests

Gemfile, Gemfile.lock, lua/neotest-rspec/init.lua, spec/its/its_spec.rb, spec/its/its_spec_01.commands, spec/its/its_spec_01.expected, spec/its/its_spec_02.commands, spec/its/its_spec_02.expected, spec/its/its_spec_03.commands, spec/its/its_spec_03.expected, spec/its/its_spec_04.commands, spec/its/its_spec_04.expected, spec/its/its_spec_05.commands, spec/its/its_spec_05.expected, tests/unit/rspec/its_spec.lua
This adds support for [rspec-its](https://github.com/rspec/rspec-its).
It's an outdated style of specs but I happen to work on older projects that use it. It would be nice if the support were baked into this project. 😄
=> feat: add support for rspec-its style specs

README.md, lua/neotest-rspec/init.lua
Allows debug tests to be invoked through neotest.
I've tested locally and it works as expected with nearest test, but it would also be worth testing with a minimal file. If you want me to add some tests for this I'm happy to 😄 
Thanks for a great package!
=> Add support for dap to debug tests

lua/neotest-rspec/init.lua, neotest_formatter.rb
This PR fixes #74 by shipping a custom formatter with the plugin and referencing it when running the tests instead of the built-in JSON formatter. 
All tests are now passing in the repo with this patch applied.
=> fix: add custom formatter to solve nested examples issue

README.md, lua/neotest-rspec/config.lua, lua/neotest-rspec/init.lua
This PR resolves the issue #77  where tests could not be executed in a Docker environment due to a custom formatter load error by adding a formatter configuration option.
The load error occurred because `neotest_formatter.rb` exists in the user’s local environment but not in the Docker container environment, and the custom formatter was specified by default.
The default value of the formatter option remains `NeotestFormatter`, so it does not affect existing test executions. For test executions in a Docker environment, the load error can be resolved by setting the formatter option to "json".
This is an existing bug, but when running tests in a Docker environment that include `shared_examples`, an error occurs. Allowing the use of a custom formatter in a Docker environment could potentially …
=> Add `formatter` configuration option to perform tests in Docker environment

lua/neotest-rspec/init.lua
I get an error message:
> Config needs the `request` property which must be one of `attach` or `launch`
https://github.com/user-attachments/assets/2c24dd53-6f5b-4e77-94e5-a910139d603f
1. References [`nvim-dap-ruby`'s base ruby adapter configurations](https://github.com/suketa/nvim-dap-ruby/blob/4176405d186a93ebec38a6344df124b1689cfcfd/lua/dap-ruby.lua#L98) to resolve the above error message by adding `request = "attach",` to the return of `get_strategy_config`
2. Suppresses `exit code 1` notices from `nvim-dap-ruby` by configuring `error_on_failure = false`
3. Copies the `localfs = true,` and `waiting = 1000` configuration to match the [`nvim-dap-ruby`'s base run configuration](https://github.com/suketa/nvim-dap-ruby/blob/4176405d186a93ebec38a6344df124b1689cfcfd/lua/dap-ruby.lua#L99)
1. …
=> fix: update nvim-dap-ruby strategy config

README.md, engine/spec/engine_spec.rb, engine/spec/engine_spec_01.commands, engine/spec/engine_spec_01.expected, engine/spec/engine_spec_02.commands, engine/spec/engine_spec_02.expected, lua/neotest-rspec/config.lua, lua/neotest-rspec/init.lua, tests/template.lua, tests/unit/rspec/engine_spec.lua
Support for running specs for isolated engines was originally added in #34. However, it was broken by a tweak made in #49 that wanted to support running nested spec suites from the project root instead.
I may have got this wrong, but I'm interpreting that as inadvertent breakage for engines (as none of the supporting code was removed), so I'm submitting this PR to restore the original behaviour. As it is evidently not behaviour that everyone prefers, I've suggested an `engine_support = true` default configuration; those that would rather continue with the "broken" behaviour could change this to opt out. But it could equally make sense to continue with the current behaviour as the default, and allow opt in back to the original enhanced support?
I've added some new coverage, as it looks to …
=> Fix broken engine support
